### ISSUE TITLE
failed to calculate float divide by zero

### ISSUE THREAD

**Issue by jordy101091** [Ernst79/degree-days#20]
This is the exception from the Hassio Logs

`Deze fout is ontstaan door een aangepaste integratie.

Logger: custom_components.degree_days
Source: helpers/update_coordinator.py:300
Integration: Degree-Days
First occurred: 23:52:12 (15 occurrences)
Last logged: 23:59:07

Unexpected error fetching Degree Days data: float division by zero
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 300, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/degree_days/__init__.py", line 117, in _async_update_data
    data = await self.hass.async_add_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/degree_days/knmi/__init__.py", line 19, in __init__
    data = self.get_degree_days()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/degree_days/knmi/__init__.py", line 90, in get_degree_days
    gas_consumption_total = self.gas_usage * number_of_days_knmi / number_of_days_gas
                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
ZeroDivisionError: float division by zero
`

**Comment by nelbs** [comment]
There seems to be a problem with the knmi api. The data from this year is not yet available. When it becomes available everything should work again.

**Comment by Ernst79** [comment]
Fixed in 0.9.3
